### PR TITLE
customize employee_id && client details for appointment queries

### LINKED ISSUE #60: Customizable Employee ID
# Bug Report

---
## 1.Bug URL:

`/employees`

## 2.Date Created: 

March 10, meeting with PO

## 3.Defect Description:

PO wants to be able to assign an arbitrary ID to employee to facilitate management of their IDs. 

## 4.Resolution: 

Database will have to change and need to check for uniqueness. 

## 5.Resolution Date:

See activity history on this issue. 

## 6.Screenshot Bug: 

N/A

---

### PR DESCRIPTION
**Pull request by Alex-DSJ**
# Description

This add a feature to allow the user to customized the employee_id
This will provide client details for appointment queries

---

# Related Jira Issue (ID/URL)

N/A

# Related GitHub Issues

- This fixes #60, #61.

# Checklist

- [X] Code compiles correctly
- [X] Code is covered by current tests or new tests
- [X] Code is formatted correctly
- [X] Extended the README / documentation, if necessary

---

# Comment/Discussion

modification based on new requirements from stakeholders and frontend developers.

### CODE REVIEW

File: backend/src/models/syncTables.ts [hunk 1]
```diff
@@ -15,13 +15,13 @@ const syncTables = async () => {
       ServiceModel.sync({ alter: true }),
       ComboModel.sync({ alter: true }),
       EmployeeModel.sync({ alter: true }),
-      AppointmentModel.sync({ alter: true }),
+      Customer.sync({ alter: true }),
```
Comment (yuxiang-zhang) [inline backend/src/models/syncTables.ts:18]: I suggest aliasing `Customer as CustomerModel` for consistency.

File: backend/src/models/syncTables.ts [hunk 2]
```diff
@@ -15,13 +15,13 @@ const syncTables = async () => {
...
     ]);
+    await AppointmentModel.sync({ alter: true });
     await ServiceComboModel.sync({ alter: true });
     await EmployeeServiceModel.sync({ alter: true });
     await AppointmentEmployeeModel.sync({ alter: true });
     await AppointmentServiceModel.sync({ alter: true });
-    await Customer.sync({ alter: true });
     await Appointment.sync({ alter: true });
```
Comment (yuxiang-zhang) [inline backend/src/models/syncTables.ts:25]: This model will not be used to store Appointment instances. All code (e.g. `appointment.model.ts`) related to this model are effectively *dead code* and should therefore be removed.

File: backend/src/services/appointment-service.ts [hunk 3]
```diff
@@ -125,6 +150,7 @@ class AppointmentService extends GeneralService<IAppointmentJson, IAppointmentDt
         { where: { id } }
       );
       await t.commit();
+      return;
```
Comment (yuxiang-zhang) [inline backend/src/services/appointment-service.ts:153]: The frontend expects a return value that can be parsed as JSON. Returning `void` as response will cause the frontend `util.http` method to crash.

**Review by yuxiang-zhang — CHANGES_REQUESTED** [review]

**Review by NJLprograms — APPROVED** [review]

**Review by yuxiang-zhang — APPROVED** [review]
