### PR TITLE
Fix/appm calendar view

### LINKED ISSUE #69: some modifications requests on the module appointment.
# Bug Report Format

---
## 1.Bug URL:

#64 

## 2.Date Created: 

April. 03. 2022

## 3.Defect Description:

_Description of the defect. 

- [x] calendar grid display information has problem.
- [x] appointment time extension has an error due to male function of code.

## 4.Resolution: 

- change generateSchedules.ts along with tuiTemplateConfig.js file: return the schedule title instead of whole detailed information.
- create new date object either by new Date or moment.js

## 5.Resolution Date:

Both has been solved by April. 03. 2022

## 6.Screenshot Bug: 
For the display information problem
image

For the time extension problem
image

---

### PR DESCRIPTION
**Pull request by successsb89**
# Description

Fixed bugs of #69 

- [x] calendar grid display information has problem.
- [x] appointment time extension has an error due to male function of code.

---

# Related Jira Issue (ID/URL)

None

# Related GitHub Issues

- This fixes #69 

# Checklist

- [x] Code compiles correctly
- [x] Code is covered by current tests or new tests
- [x] Code is formatted correctly
- [x] Extended the README / documentation, if necessary

---

# Comment/Discussion
After fixing the display information
image

After fixing the time extension
image
: can adjust the time by dragging each appointment and will give the confirmation in the end.

### CODE REVIEW

File: frontend/components/appointment/dropConfirmationDialog.js [hunk 1]
```diff
@@ -26,8 +26,8 @@ const ConfirmationDialog = (props) => {
                     <div>{'Previous start at: ' + ((updateEvent && updateEvent.schedule) ? updateEvent.schedule.start._date.toString().substr(4, 20) : '')}</div>
```
Comment (yuxiang-zhang) [inline frontend/components/appointment/dropConfirmationDialog.js:26]: While at it, these two lines seem to be prone to similar issues.

**Review by yuxiang-zhang — CHANGES_REQUESTED** [review]

File: frontend/components/appointment/dropConfirmationDialog.js (hunk 1 above)
Comment (yuxiang-zhang) [reply frontend/components/appointment/dropConfirmationDialog.js:26]: Tui Calendar use another type of Date object, that may not have `_date` property
it's called `TZDate`, not the same as plain js `Date` objects
also sometimes `start` and `end` can be strings instead of `Date` objects
that's why we got the issue for the two lines you changed
looking at these four lines, I think it's reasonable to say they are similar and can result in similar bugs

**Review by yuxiang-zhang — APPROVED** [review]

**Review by kimchhengheng — APPROVED** [review]
